<div class="uk-overflow-auto uk-margin-medium-bottom uk-margin-medium-top">
    <table class="uk-table uk-table-hover uk-table-divider">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Cognome</th>
                <th>Mail</th>
                <th>Matricola</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Andrea</td>
                <td>Pulita</td>
                <td>andrea.pulita@studio.unibo.it</td>
                <td>825934</td>
            </tr>
            <tr>
                <td>Riccardo</td>
                <td>Romagnoli</td>
                <td>riccardo.romagnoli3@studio.unibo.it</td>
                <td>832198</td>
            </tr>
            <tr>
                <td>Alessandro</td>
                <td>Talmi</td>
                <td>alessandro.talmi@studio.unibo.it</td>
                <td>832060</td>
            </tr>
        </tbody>
    </table>
</div>